[package]
name = "yearfloatclock"
version = "1.0.0"
authors = ["Bill Fraser <bill@wfraser.dev>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = { version = "0.3.34", features = ["local-offset", "parsing"] }
